# Generated by Django 3.2.7 on 2021-09-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_name_basics_title_basics_title_principals_title_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieid', models.CharField(max_length=5)),
                ('imdbid', models.CharField(max_length=10)),
                ('tmdbid', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieid', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=100)),
                ('geners', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=5)),
                ('titleid', models.CharField(max_length=5)),
                ('rating', models.CharField(max_length=5)),
                ('timestamp', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=5)),
                ('titleid', models.CharField(max_length=5)),
                ('tag', models.CharField(max_length=100)),
                ('timestamp', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='name_basics',
        ),
        migrations.DeleteModel(
            name='title_basics',
        ),
        migrations.DeleteModel(
            name='title_principals',
        ),
        migrations.DeleteModel(
            name='title_ratings',
        ),
    ]
